### ISSUE TITLE
size_t should be an unsigned type

### ISSUE THREAD

**Issue by clausecker** [lkundrak/dev86#12]
In your current libc, `size_t` is a `typedef` for `int`. As per ISO 9899, it should be an unsigned type.

**Comment by jbruchon** [comment]
Fixed in https://github.com/jbruchon/dev86/commit/74753fa024ef5fec0261702d6d18a3773c44b62e

**Comment by clausecker** [comment]
Please also make sure that `sizeof` returns an `unsigned`.

**Comment by jbruchon** [comment]
```
dev86 $ grep -n sizeof bcc/*.c
...snip...
bcc/express.c:14:PRIVATE unsigned insizeof;     /* nest level for getsizeof */
```

Honestly, I'm not sure where in the spaghetti mess of `bcc` they hide it, but everywhere I see something related to `sizeof` I see `unsigned` beside it.
