### ISSUE TITLE
__mkargv es register changed, program name missing in argv[0]

### ISSUE THREAD

**Issue by anchorz** [lkundrak/dev86#5]
in __mkargv.o the es register is modified during the processing of the arguments and never restored. At the same time we can correct the missing program name the arg[0].

extern int __psp;
extern int __envseg;

void set_program_name(__argv)
char ** __argv;
{
    unsigned char *ptr;
    int src,len;
    
    __set_es(__envseg);
    src=0;
    while(__peek_es(src++)!=0)
    {
    	while(__peek_es(src++)!=0);
    }
    src+=2; // step over 0x0001
    len=0;
    while (__peek_es(src+len++)!=0);
    ptr=sbrk(len);
    __argv[0]=ptr;
    while(len--)
    {
    	*ptr++=__peek_es(src++);
    }
}

__mkargv(__argc, __argv)
int __argc;
char ** __argv;
{
   int length, i, argc=1, s=0;
   unsigned char *ptr, *p;
   int es=__get_es();
 
   set_program_name(__argv);
   
   __set_es(__psp);    		/* Pointer to the args */
....
   __set_es(es);
}

**Comment by lkundrak** [comment]
Applied, thanks.

**Comment by mfld-fr** [comment]
Sorry for the mixing of the issues, latest commit actually related to mfld-fr#5, not this one.
