### ISSUE TITLE
ar.c rename of temporary libary fails on some platforms

### ISSUE THREAD

**Issue by anchorz** [lkundrak/dev86#6]
if the destination already exists, rename (tempname, archive) will fail, add unlink() first:

ar.c:
  if (!appendflag)
  {
	unlink(archive);
    if (rename (tempname, archive))
	{
	  printf("rename failed %d %s\n",errno,strerror(errno));
      pfatal_with_name (tempname);
	}
 }

**Comment by lkundrak** [comment]
Merged, thanks!

**Comment by mfld-fr** [comment]
Sorry for the mixing of the issues, latest commit actually related to mfld-fr#6, not this one.
